### ISSUE TITLE
협업 약속 추가 제의

### ISSUE THREAD

**Issue by csee22-076** [2023OSSL3576/shopingmall#1]
1. 함수나 조건문, 반복문 작성 시 소괄호 바로 뒤에 중괄호를 붙히는 건지 아닌지 명시했으면 좋겠습니다. 아래 예는 붙인 경우이고 저는 붙이는 걸 선호합니다. 
     if(a == 2){ 
         b = 3;
     }

2. 연산자 앞뒤로 띄어쓸 것인지 아닌지 명시했으면 좋겠습니다. 아래 예는 앞뒤로 띄어쓴 것이고 저는 띄어쓰는 것을 선호합니다.
    a += 3;

**Comment by GoldenWo1f** [comment]
1. 저도 소괄호 뒤에 바로 중괄호를 붙이는 것을 선호합니다.

2. 저도 연산자 앞뒤로 띄어쓰기 하는 것을 선호하기는 하지만 반복문이나 조건문에서는 띄어쓰기를 하지 않습니다. 이번 협업을 하는 동안에는 반복문이나 조건문에도 띄어쓰기를 하겠지만 기존의 습관때문에 이를 지키지 못할 수도 있다는 점 양해 바랍니다.
    ex) for(int i=0; i<5; i++)

**Comment by csee22-076** [comment]
2번에서 그러면 반복문이나 조건문에는 띄어쓰기를 하지 않는 걸로 하겠습니다!
