### ISSUE TITLE
프로그램 문답 형식

### ISSUE THREAD

**Issue by csee22-076** [2023OSSL3576/shopingmall#6]
프로그램에서 문답 형식을 정했으면 좋겠습니다.
질문
1. 이름: 
2. 이름은?
3. 이름?
답
1. 저장되었습니다.
2. -> 저장되었습니다
3. ->저장되었습니다.
4. => 저장되었습니다.
5. =>저장되었습니다.

저는 주로 질문에서는 1번 형식을, 답에서는 5번 형식을 사용합는데 추가로 의견 있으시면 말씀해주세요

**Comment by GoldenWo1f** [comment]
저는 주로 사용하는 형식 없이 그때그때 다르게 사용합니다.
혼동이 생길 수도 있으니 아무런 기호도 사용하지 않는 1번과 4번으로 하는 것이 좋지 않을까요?

**Comment by csee22-076** [comment]
좋습니다!
